# Generated by Django 2.2.1 on 2019-11-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tredn_Sig_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('CoinName', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=30)),
                ('Signal', models.CharField(max_length=30)),
                ('Profit', models.CharField(max_length=30)),
            ],
        ),
    ]
